### ISSUE TITLE
How to match files on Windows?

### ISSUE THREAD

**Issue by marek-hanzal** [gajus/turbowatch#20]
Hello,

I'm trying to setup turbowatch (2.3.2) with
```js
export default watch({
    project: __dirname,
    triggers: [
        {
            initialRun: false,
            expression: [
                "anyof",
                [
                    "match",
                    "src/**/*.**",
                    'wholename'
                ],
                [
                    "match",
                    "*.json",
                    "basename",
                ],
            ],
            name:       "build",
            onChange:   async ({spawn}) => {
                await spawn`npm run build:esbuild`;
                await spawn`npm run build:types`;
            },
        },
    ],
});
```

This was my original attempt or a way how I was expected it would work:
```js
watch({
    project,
    triggers: [
        {
            initialRun: false,
            expression: [
                "anyof",
                [
                    "dirname",
                    "src",
                ],
                [
                    "match",
                    "*.json",
                    "basename",
                ],
            ],
            name:       "build",
            onChange:   async ({spawn}) => {
                await spawn`npm run build:esbuild`;
                await spawn`npm run build:types`;
            },
        },
    ],
})
```

But with the new version (when moved from watchman) I cannot (or don't know how) setup watching just subtree of the project. Json files are catched correctly, but watching in `src` does not work (means not triggered). Please, what am I doing wrong or how to setup the thing correctly?

The idea is I've god .ts files generated in the `lib`, so when a new `.d.ts` files appears, turbowatch triggeres again, so I just want to watch `src` and a few other files (package.json, tsconfig, ...).

Thank you!

**Comment by marek-hanzal** [comment]
Soo, one moment:
![image](https://user-images.githubusercontent.com/13855126/226181227-541040bd-aeab-439a-b885-c829b786e36e.png)

I'm on windows, thus I'm getting `\`, so adding `/` won't trigger the stuff... now I'll try to investigate micromatch and how it should work.

**Comment by marek-hanzal** [comment]
Ok, it was quite a fun find it, but I get it:
![image](https://user-images.githubusercontent.com/13855126/226181850-d8938c51-ee31-4dbd-b6ed-f9bd9c4fb88a.png)

Maybe it would be nice to extend docs and put reference to the individual matchers (dirname with `/` as it would not work on Win) and usage of Micromatch, so people can overcome it without messing with your source code to find, how the thing works.

I don't want to sound rude, I'm happy I've found your lib, so at least I can say - good work.

**Comment by gajus** [comment]
I am not a windows user, so cannot easily debug and/or fix this, but PR is welcome. We can add windows to the test matrix as well.
