### ISSUE TITLE
Better updated docs for shutdown and abort controller

### ISSUE THREAD

**Issue by DesignByOnyx** [gajus/turbowatch#44]
The docs describe [gracefully terminating](https://github.com/gajus/turbowatch#gracefully-terminating-turbowatch) with examples using an abort signal or a shutdown method, neither of which are available:

![image](https://user-images.githubusercontent.com/514040/231291454-561a6574-69e8-467f-b18a-3961f600cf90.png)

Is there a recommended way to gracefully terminate?

**Comment by DesignByOnyx** [comment]
OK - I see that I can `await watch(...)` to get the controller. I'll keep this open so the docs get updated, and I'd like feedback on the abort signal as I'd prefer use that.

**Comment by gajus** [comment]
Where in documentation does this lack clarity?

**Comment by DesignByOnyx** [comment]
The screenshot shows what is wrong with the current docs, I'll summarize here:

1. `const { shutdown } = watch(...)` does not work. You must `await watch(...)`.
2. `abortSignal` is not a valid option, though this would be really nice to have.

https://github.com/gajus/turbowatch/compare/main...DesignByOnyx:designbyonyx/docs-update?expand=1

**Comment by gajus** [comment]
> abortSignal is not a valid option, though this would be really nice to have.

What benefit would that have over the current `shutdown` method?

**Comment by DesignByOnyx** [comment]
> What benefit would that have over the current shutdown method?

Shutdown works fine. It would just be nice alternative to `shutdown` which reinforces a good pattern for dealing with multiple related async tasks. It's not a big deal though. I really appreciate all the work you've done!

**Comment by gajus** [comment]
FYI it's been added.
